services:
  api_inteligente:
    build: .
    container_name: api_inteligente
    ports:
      - "8000:8000"
    environment:
      DATABASE_PATH: /app/app_data/riesgo_academico.db
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SENDER_EMAIL: alertas@universidad.local
    volumes:
      - ./models:/app/models:ro
      - ./app_data:/app/app_data
    depends_on:
      - mailhog
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_orquestador
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: America/Lima
      TZ: America/Lima
      N8N_SECURE_COOKIE: "false"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - api_inteligente
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog_local
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  n8n_data:
